<?php
declare(strict_types=1);
/* DIAGNOSTIC TEMPORAIRE : supprimer après utilisation. */
$diagnosticKey='KOVA-DIAG-7f2c9a41';
function esc(string $v): string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
function envValues(string $file):array{$out=[];foreach(is_file($file)?(file($file,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[]):[] as $line){$line=trim($line);if($line===''||str_starts_with($line,'#')||!str_contains($line,'='))continue;[$k,$v]=explode('=',$line,2);$out[trim($k)]=trim($v," \t\n\r\0\x0B\"'");}return $out;}
$key=(string)($_GET['key']??$_POST['key']??'');$authorized=hash_equals($diagnosticKey,$key);$result=null;$error='';
if($authorized&&($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&isset($_POST['gateway_token'])){
 $base=rtrim((string)($_POST['base_url']??''),'/');$token=trim((string)$_POST['gateway_token']);$mode=(string)($_POST['mode']??'handshake');
 if(!filter_var($base,FILTER_VALIDATE_URL)||strlen($token)<8)$error='URL ou jeton invalide.';else{
  $path=$mode==='publish'?'/api/gateway/publications':'/api/gateway/handshake';$payload=$mode==='publish'?json_encode(['content'=>'Diagnostic privé KOVA — supprimer cette publication après le test.','visibility'=>'private','source'=>'gateway_diagnostic']):null;
  $headers=['Accept: application/json','Authorization: Bearer '.$token];if($payload!==null){$headers[]='Content-Type: application/json';$headers[]='X-Requested-With: XMLHttpRequest';}
  $ch=curl_init($base.$path);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$mode==='publish'?'POST':'GET',CURLOPT_HTTPHEADER=>$headers,CURLOPT_POSTFIELDS=>$payload,CURLOPT_CONNECTTIMEOUT=>8,CURLOPT_TIMEOUT=>20,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2]);$body=curl_exec($ch);$curlError=curl_error($ch);$status=(int)curl_getinfo($ch,CURLINFO_HTTP_CODE);$contentType=(string)curl_getinfo($ch,CURLINFO_CONTENT_TYPE);curl_close($ch);
  $decoded=json_decode((string)$body,true);$result=['test'=>$mode==='publish'?'publication privée':'handshake','endpoint'=>$path,'status'=>$status,'content_type'=>$contentType,'curl_error'=>$curlError,'body_length'=>strlen((string)$body),'json_valid'=>is_array($decoded),'top_level_keys'=>is_array($decoded)?array_keys($decoded):[],'body_preview'=>mb_substr((string)$body,0,5000)];
 }
}
$env=envValues(__DIR__.'/.env');
?><!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Diagnostic passerelle KOVA</title><style>body{font-family:Arial,sans-serif;background:#f3f6fb;color:#162033;padding:24px}.card{max-width:780px;margin:auto;background:#fff;border-radius:18px;padding:24px;box-shadow:0 14px 45px #0f172a18}label{display:block;font-weight:700;margin:14px 0}input{display:block;width:100%;box-sizing:border-box;margin-top:6px;border:1px solid #ccd5e1;border-radius:10px;padding:12px}button{border:0;border-radius:10px;padding:12px 16px;background:#315cf6;color:#fff;font-weight:700;margin:4px}.notice{padding:12px;border-radius:10px;background:#fff0f2;color:#a51f3b;margin:14px 0}.ok{background:#edf9f4;color:#147653;padding:12px;border-radius:10px}.muted{color:#67758a;font-size:13px}pre{white-space:pre-wrap;overflow:auto;background:#101827;color:#d5e2ff;padding:14px;border-radius:10px;font-size:12px}</style></head><body><main class="card"><h1>Diagnostic passerelle KOVA</h1><?php if(!$authorized): ?><p class="muted">Ajoutez la clé diagnostic dans l’URL :</p><p><code>?key=KOVA-DIAG-7f2c9a41</code></p><?php else: ?><div class="ok">Diagnostic autorisé. Les secrets ne sont pas affichés.</div><p class="muted">Handshake : aucun contenu créé. Publication privée : crée un seul post privé de diagnostic pour afficher la réponse exacte.</p><form method="post"><input type="hidden" name="key" value="<?=esc($key)?>"><label>URL de la plateforme principale<input name="base_url" value="<?=esc((string)($_POST['base_url']??'https://mconnect.gamer.free'))?>" required></label><label>Jeton gateway<input type="password" name="gateway_token" autocomplete="off" required></label><button name="mode" value="handshake">Tester le handshake</button><button name="mode" value="publish">Tester la publication privée</button></form><?php if($error): ?><div class="notice"><?=esc($error)?></div><?php endif;?><?php if($result): ?><h2>Réponse brute</h2><pre><?=esc(json_encode($result,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES))?></pre><p class="muted">Ne partagez pas le jeton. Supprimez ce fichier après le diagnostic.</p><?php endif;?><h2>Configuration détectée</h2><pre><?=esc(json_encode(['APP_ENV'=>$env['APP_ENV']??null,'STORAGE_DRIVER'=>$env['STORAGE_DRIVER']??null,'DB_HOST_present'=>isset($env['DB_HOST']),'DB_DATABASE_present'=>isset($env['DB_DATABASE']),'CLOUDINARY_configured'=>isset($env['CLOUDINARY_CLOUD_NAME'])&&isset($env['CLOUDINARY_API_KEY'])&&isset($env['CLOUDINARY_API_SECRET'])],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE))?></pre><?php endif;?></main></body></html>
