(async function(){
  const esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const api=async(url,opts={})=>{const r=await fetch(url,{headers:{'Content-Type':'application/json','Accept':'application/json','X-Requested-With':'XMLHttpRequest','X-KOVA-CSRF':document.querySelector('meta[name="kova-csrf"]')?.content||''},...opts});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw Error(d.error||'Erreur');return d;};
  const stats=document.getElementById('admin-stats');
  try{const d=await api('/api/admin/overview');stats.innerHTML=Object.entries({Utilisateurs:d.stats.users,Publications:d.stats.posts,Signalements:d.stats.reports_open,'Demandes ouvertes':d.stats.tickets_open}).map(([k,v])=>`<div class="card stat-card"><strong>${esc(v)}</strong><span>${esc(k)}</span></div>`).join('');
  const [sp,re,us]=await Promise.all([api('/api/admin/support'),api('/api/admin/reports'),api('/api/admin/users')]);
  const sl=document.getElementById('admin-support-list'); const labels={new:'Nouveau',open:'Ouvert',in_progress:'En cours',resolved:'Résolu',closed:'Fermé'};
  sl.innerHTML=sp.tickets.length?sp.tickets.map(t=>`<article class="admin-row"><div><strong>${esc(t.subject)}</strong><small>${esc(t.user_name)} · ${esc(t.user_email)} · ${esc(t.category)}</small><p>${esc(t.message)}</p></div><select data-ticket="${esc(t.id)}"><option value="new">Nouveau</option><option value="open">Ouvert</option><option value="in_progress">En cours</option><option value="resolved">Résolu</option><option value="closed">Fermé</option></select></article>`).join(''):'<p class="muted">Aucune demande.</p>';
  sl.querySelectorAll('[data-ticket]').forEach(x=>{x.value=sp.tickets.find(t=>t.id===x.dataset.ticket)?.status||'new';x.onchange=async()=>{try{await api('/api/admin/support/status',{method:'POST',body:JSON.stringify({ticket_id:x.dataset.ticket,status:x.value})});}catch(e){alert(e.message);}}});
  const rl=document.getElementById('admin-reports-list'); rl.innerHTML=re.reports.length?re.reports.map(r=>`<article class="admin-row"><div><strong>${esc(r.reason||r.type||'Signalement')}</strong><small>${esc(r.target_type||'contenu')} · ${esc(r.created_at||'')}</small><p>${esc(r.details||r.message||'')}</p>${r.target_preview?`<blockquote class="report-preview">${esc(r.target_preview)}</blockquote>`:''}${(r.target_type==='post'||r.target_type==='comment')&&!r.target_deleted?`<button class="button button-soft danger-text" data-del-target="${esc(r.id)}">Supprimer le contenu</button>`:''}</div><select data-report="${esc(r.id)}"><option value="new">Nouveau</option><option value="reviewing">En examen</option><option value="resolved">Résolu</option><option value="dismissed">Classé</option></select></article>`).join(''):'<p class="muted">Aucun signalement.</p>';
  rl.querySelectorAll('[data-report]').forEach(x=>{x.value=re.reports.find(r=>r.id===x.dataset.report)?.status||'new';x.onchange=async()=>{try{await api('/api/admin/reports/status',{method:'POST',body:JSON.stringify({report_id:x.dataset.report,status:x.value})});}catch(e){alert(e.message);}}});
  rl.querySelectorAll('[data-del-target]').forEach(b=>b.onclick=async()=>{const r=re.reports.find(x=>x.id===b.dataset.delTarget);if(!confirm('Supprimer ce contenu ?'))return;try{await api(r.target_type==='post'?'/api/admin/posts/delete':'/api/admin/comments/delete',{method:'POST',body:JSON.stringify(r.target_type==='post'?{post_id:r.target_id}:{comment_id:r.target_id})});b.remove();}catch(e){alert(e.message);}});
  const pr=await api('/api/admin/privacy-requests'); const pl=document.getElementById('admin-privacy-list');
  const ps={new:'Nouveau',in_progress:'En cours',completed:'Traité',rejected:'Refusé'};
  pl.innerHTML=pr.requests.length?pr.requests.map(r=>`<article class="admin-row"><div><strong>${esc(r.type)}</strong><small>${esc(r.user_name)} · ${esc(r.user_email)} · ${esc(r.created_at)}</small><p>${esc(r.message||'Aucun détail')}</p></div><select data-privacy="${esc(r.id)}"><option value="new">Nouveau</option><option value="in_progress">En cours</option><option value="completed">Traité</option><option value="rejected">Refusé</option></select></article>`).join(''):'<p class="muted">Aucune demande.</p>';
  pl.querySelectorAll('[data-privacy]').forEach(x=>{x.value=pr.requests.find(r=>r.id===x.dataset.privacy)?.status||'new';x.onchange=async()=>{try{await api('/api/admin/privacy-requests/status',{method:'POST',body:JSON.stringify({request_id:x.dataset.privacy,status:x.value})});}catch(e){alert(e.message);}}});
  const ul=document.getElementById('admin-users-list'); ul.innerHTML=us.users.map(u=>`<article class="admin-row"><div><strong>${esc(u.display_name||u.email)}</strong><small>${esc(u.email)} · ${esc(u.role||'USER')} · ${esc(u.account_status||'active')}</small></div><div class="admin-actions"><select data-role="${esc(u.id)}"><option>USER</option><option>MODERATOR</option><option>ADMIN</option></select><select data-status="${esc(u.id)}"><option value="active">Actif</option><option value="suspended">Suspendu</option><option value="banned">Banni</option></select></div></article>`).join('');
  ul.querySelectorAll('[data-role]').forEach(x=>{x.value=us.users.find(u=>u.id===x.dataset.role)?.role||'USER';x.onchange=async()=>{try{await api('/api/admin/users/role',{method:'POST',body:JSON.stringify({user_id:x.dataset.role,role:x.value})});}catch(e){alert(e.message);}}});
  ul.querySelectorAll('[data-status]').forEach(x=>{x.value=us.users.find(u=>u.id===x.dataset.status)?.account_status||'active';x.onchange=async()=>{try{await api('/api/admin/users/status',{method:'POST',body:JSON.stringify({user_id:x.dataset.status,status:x.value})});}catch(e){alert(e.message);}}});
  try{
    const ap=await api('/api/admin/oauth/apps'); const al=document.getElementById('admin-apps-list');
    al.innerHTML=ap.apps.length?ap.apps.map(a=>`<article class="admin-row"><div><strong>${esc(a.name)}</strong> ${a.verified?'✅ vérifiée':''}${a.disabled?' ⛔ désactivée':''}<small>par ${esc(a.owner)} · ${esc(a.client_id)} · ${esc(a.users_count)} utilisateur(s)</small><small>${a.redirect_uris.map(esc).join(' · ')}</small></div><div class="admin-actions"><button class="button button-soft" data-verify="${esc(a.client_id)}" data-v="${a.verified?0:1}">${a.verified?'Retirer la vérification':'Marquer vérifiée'}</button><button class="button button-soft" data-disable="${esc(a.client_id)}" data-v="${a.disabled?0:1}">${a.disabled?'Réactiver':'Désactiver'}</button></div></article>`).join(''):'<p class="muted">Aucune application enregistrée.</p>';
    al.querySelectorAll('[data-verify],[data-disable]').forEach(b=>b.onclick=async()=>{const isV=b.hasAttribute('data-verify');try{await api('/api/admin/oauth/apps/update',{method:'POST',body:JSON.stringify({client_id:b.dataset.verify||b.dataset.disable,[isV?'verified':'disabled']:b.dataset.v==='1'})});location.reload();}catch(e){alert(e.message);}});
    const lg=await api('/api/admin/activity'); document.getElementById('admin-log-list').innerHTML=lg.logs.length?lg.logs.slice(0,30).map(l=>`<article class="admin-row"><div><strong>${esc(l.action)}</strong><small>${esc(l.created_at)} · ${esc(JSON.stringify(l.meta||{}))}</small></div></article>`).join(''):'<p class="muted">Aucune action enregistrée.</p>';
  }catch(e){}
  }catch(e){stats.innerHTML='<div class="card"><p>'+esc(e.message)+'</p></div>';}

  const gf=document.getElementById('admin-gateway-form');
  if(gf){
    const enabled=document.getElementById('gateway-enabled'), style=document.getElementById('gateway-style'), count=document.getElementById('gateway-count'), hours=document.getElementById('gateway-hours'), status=document.getElementById('gateway-status'), tokenResult=document.getElementById('gateway-token-result');
    try{const d=await api('/api/admin/gateway');const g=d.gateway||{};enabled.checked=!!g.enabled;style.value=g.style||'';count.value=g.posts_per_day||1;hours.value=(g.publish_hours||[]).join(', ');status.textContent=g.token_prefix?'Jeton actif ('+g.token_prefix+'…).':'Aucun jeton actif.';}catch(e){status.textContent=e.message;}
    gf.onsubmit=async ev=>{ev.preventDefault();status.textContent='Enregistrement…';try{await api('/api/admin/gateway',{method:'POST',body:JSON.stringify({enabled:enabled.checked,style:style.value,posts_per_day:Number(count.value),publish_hours:hours.value.split(',').map(x=>x.trim()).filter(Boolean)})});status.textContent='Configuration enregistrée.';}catch(e){status.textContent=e.message;}};
    document.getElementById('gateway-rotate').onclick=async()=>{if(!confirm('Le nouveau jeton invalidera l’ancien. Continuer ?'))return;try{const d=await api('/api/admin/gateway/token',{method:'POST',body:'{}'});tokenResult.hidden=false;tokenResult.textContent='Copiez ce jeton maintenant : '+d.token;status.textContent='Jeton renouvelé.';}catch(e){status.textContent=e.message;}};
  }

  const legacyScan=document.getElementById('legacy-images-scan'), legacyRun=document.getElementById('legacy-images-run'), legacyLimit=document.getElementById('legacy-images-limit'), legacyStatus=document.getElementById('legacy-images-status'), legacyList=document.getElementById('legacy-images-list');
  if(legacyScan&&legacyRun){
    legacyScan.onclick=async()=>{legacyStatus.textContent='Analyse…';try{const d=await api('/api/admin/post-images');legacyRun.disabled=!d.total;legacyStatus.textContent=d.total+' image(s) à traiter.';legacyList.innerHTML=d.items.length?d.items.map(x=>`<article class="admin-row"><div><strong>Publication ${esc(x.id)}</strong><small>${esc(x.created_at||'')} · ${esc(x.image_url)}</small></div></article>`).join(''):'<p class="muted">Aucune ancienne image externe à traiter.</p>';}catch(e){legacyStatus.textContent=e.message;}};
    legacyRun.onclick=async()=>{legacyRun.disabled=true;legacyScan.disabled=true;legacyStatus.textContent='Traitement…';try{const d=await api('/api/admin/post-images',{method:'POST',body:JSON.stringify({limit:Number(legacyLimit.value)||5})});legacyStatus.textContent=d.migrated+' image(s) migrée(s) sur '+d.processed+'.';legacyList.innerHTML=d.results.map(x=>`<article class="admin-row"><div><strong>${x.ok?'Image stockée chez KOVA':'Échec du traitement'}</strong><small>${esc(x.id)} · ${esc(x.error||x.image_url||'')}</small></div></article>`).join('');}catch(e){legacyStatus.textContent=e.message;}finally{legacyScan.disabled=false;}};
  }

  const mf=document.getElementById('admin-maintenance-form');
  if(mf){
    const enabled=document.getElementById('maintenance-enabled'), start=document.getElementById('maintenance-start'), end=document.getElementById('maintenance-end'), msg=document.getElementById('maintenance-message'), status=document.getElementById('maintenance-status');
    const localValue=iso=>{if(!iso)return ''; const d=new Date(iso); if(Number.isNaN(d.getTime()))return ''; const p=n=>String(n).padStart(2,'0'); return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`;};
    const loadMaintenance=async()=>{try{const d=await api('/api/admin/maintenance');const m=d.maintenance||{};enabled.checked=!!m.enabled;start.value=localValue(m.start_at);end.value=localValue(m.end_at);msg.value=m.message||'';status.textContent=m.active?'Maintenance actuellement active.':'Maintenance inactive.';}catch(e){status.textContent=e.message;}};
    loadMaintenance();
    mf.onsubmit=async ev=>{ev.preventDefault();status.textContent='Enregistrement…';try{const d=await api('/api/admin/maintenance',{method:'POST',body:JSON.stringify({enabled:enabled.checked,start_at:start.value,end_at:end.value,message:msg.value})});status.textContent=d.maintenance?.active?'Maintenance active.':'Maintenance enregistrée.';}catch(e){status.textContent=e.message;}};
  }
})();
